version: '3'

services:
  ghost:
    image: ghost:5-alpine
    ports:
      - "2368:2368"
    environment:
      - NODE_ENV=development
      - url=http://localhost:2368
    volumes:
      # Mount the current directory as the theme
      - .:/var/lib/ghost/content/themes/ghost-bulletin
      # Persist Ghost content
      - ghost-content:/var/lib/ghost/content

volumes:
  ghost-content: